---
  - name: "Install mysql"
    yum:
      name: "{{item}}"
      state: present
    loop:
      "{{mariadb}}"

  - name: "start mariadb server"
    systemd:
      name: mariadb
      state: started
      enabled: yes

  - name: "Delete anonymous users"
    mysql_user:
      user=""
      state="absent"

  - name: "Set root password"
    mysql_user:
      user=root
      password="{{db_password}}"
      host=localhost

  - name: "restart mariadb server"
    systemd:
      name: mariadb
      state: restarted
      enabled: yes